name = "RaylibCompileTest"
uuid = "81e4a17f-db78-4de8-9b17-36be982fe133"
version = "0.1.0"
authors = ["Hung Nguyen Duc <ndgnuh@protonmail.com>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Raylib = "681baf3e-1d1e-48c9-b5e5-b1aea2d6d4d9"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Accessors = "0.1.43"
FixedPointNumbers = "0.8.5"
LinearAlgebra = "1.12.0"
Random = "1.11.0"
Raylib = "0.2.0"
StaticArrays = "1.9.15"
TOML = "1.0.3"
UnPack = "1.0.2"
